### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by cyril-tl** [Code-Pop/from-vuex-to-pinia#2]
Hello, right from the beginning of lesson 03, I get this error from the call to get the list of events.

In console : 
"GET http://localhost:3000/events net::ERR_CONNECTION_REFUSED"

In Network -> Headers : 
"[warning icon] Provisional headers are shown" 

With only this link as a helper "Learn more https://developer.chrome.com/docs/devtools/network/reference/?utm_source=devtools#provisional-headers"

Can anyone help me with this?

**Comment by bencodezen** [comment]
Weird! Can you provide more instructions on how to replicate this? 

I checked out the `03-Begin` branch and it looks like everything works on my end.

**Comment by Upamo** [comment]
Are you sure that json-server is up and running? As I described in Pull Request #1 I had the problem that json-server did not start on Windows with the predefined `npm run dev` script.
If json-server is up and running it could be a problem with your local firewall settings.

**Comment by bencodezen** [comment]
Ah! So we may have figured this out, are you on Windows?

**Comment by cyril-tl** [comment]
Yes, Windows 10, version 21H2

**Comment by bencodezen** [comment]
Got it. Most likely this is caused by the command to run two simultaneous things at once:

`"dev": "vite & json-server --watch db.json",`

One way around this is to open two different terminal windows and run the `dev` and `db` command separately so that everything is up and running as intended:

```
npm run dev

npm run db
```

You can find these commands in `package.json`. Let me know if you run into any further issues!
